// HTML page for ESP-NOW radio control webserver
#ifndef WEBSERVER_PAGE_H
#define WEBSERVER_PAGE_H

static const char *html_page = 
    "<!DOCTYPE html>\n"
    "<html>\n"
    "<head>\n"
    "  <meta charset='UTF-8'>\n"
    "  <meta name='viewport' content='width=device-width, initial-scale=1.0'>\n"
    "  <title>ESP Radio Control</title>\n"
    "  <style>\n"
    "    body { font-family: Arial, sans-serif; max-width: 600px; margin: 50px auto; padding: 20px; background: #1a1a1a; color: #e0e0e0; }\n"
    "    h1 { color: #ffffff; }\n"
    "    h2 { color: #e0e0e0; font-size: 1.1em; margin-top: 25px; border-bottom: 2px solid #4CAF50; padding-bottom: 5px; }\n"
    "    .form-group { margin: 15px 0; background: #2a2a2a; padding: 15px; border-radius: 5px; }\n"
    "    .status-section { background: #2a2a2a; padding: 15px; border-radius: 5px; margin: 15px 0; border-left: 4px solid #2196F3; }\n"
    "    .status-item { margin: 10px 0; display: flex; justify-content: space-between; align-items: center; }\n"
    "    .status-label { font-weight: bold; color: #b0b0b0; }\n"
    "    .status-value { color: #64B5F6; font-family: monospace; }\n"
    "    .status-connected { color: #66BB6A; }\n"
    "    .status-disconnected { color: #EF5350; }\n"
    "    .led-pattern { margin: 15px 0; padding: 10px; background: #333333; border-left: 3px solid #FF9800; border-radius: 3px; }\n"
    "    .led-state { font-weight: bold; color: #FFB74D; }\n"
    "    .pattern-timing { font-size: 0.9em; color: #a0a0a0; font-family: monospace; }\n"
    "    label { display: block; margin-bottom: 5px; font-weight: bold; color: #b0b0b0; }\n"
    "    input[type='text'], input[type='number'], select { width: 100%; padding: 8px; border: 1px solid #444; border-radius: 4px; box-sizing: border-box; background: #333; color: #e0e0e0; }\n"
    "    button { background: #4CAF50; color: white; padding: 10px 20px; border: none; border-radius: 4px; cursor: pointer; width: 100%; margin-top: 10px; }\n"
    "    button:hover { background: #45a049; }\n"
    "    .reset { background: #f44336; margin-top: 20px; }\n"
    "    .reset:hover { background: #da190b; }\n"
    "  </style>\n"
    "</head>\n"
    "<body>\n"
    "  <h1>ESP Radio Control Config</h1>\n"
    "\n"
    "  <div class='status-section'>\n"
    "    <h2>Device Information</h2>\n"
    "    <div class='status-item'>\n"
    "      <span class='status-label'>This Device MAC:</span>\n"
    "      <span id='deviceMac' class='status-value' style='color: #FFB74D; font-weight: bold;'>Loading...</span>\n"
    "    </div>\n"
    "    <div style='margin: 10px 0; padding: 10px; background: #333; border-radius: 4px; border-left: 3px solid #FFB74D;'>\n"
    "      <p style='margin: 0; font-size: 0.85em; color: #a0a0a0;'>Copy this MAC address and enter it as <strong>Peer MAC</strong> on the other ESP32 device to establish connection.</p>\n"
    "    </div>\n"
    "  </div>\n"
    "\n"
    "  <div class='status-section'>\n"
    "    <h2>Connection Status</h2>\n"
    "    <div class='status-item'>\n"
    "      <span class='status-label'>Peer Connection:</span>\n"
    "      <span id='connStatus' class='status-value status-disconnected'>Disconnected</span>\n"
    "    </div>\n"
    "    <div class='status-item'>\n"
    "      <span class='status-label'>Signal Strength:</span>\n"
    "      <span id='rssiValue' class='status-value'>N/A</span>\n"
    "    </div>\n"
    "    <div class='status-item'>\n"
    "      <span class='status-label'>LED Pattern:</span>\n"
    "      <span id='ledPattern' class='status-value'>Initializing...</span>\n"
    "    </div>\n"
    "  </div>\n"
    "\n"
    "  <div class='status-section'>\n"
    "    <h2>LED Indicators</h2>\n"
    "    <p style='color: #666; font-size: 0.9em;'>The status LED provides feedback about device operation:</p>\n"
    "    <div class='led-pattern'>\n"
    "      <div class='led-state'>State A: Disconnected</div>\n"
    "      <div class='pattern-timing'>Pattern: ■ 1000ms ON | ■ 1000ms OFF (2000ms cycle)</div>\n"
    "      <div style='color: #666; font-size: 0.9em;'>ESP-NOW not receiving packets, normal operation mode</div>\n"
    "    </div>\n"
    "    <div class='led-pattern'>\n"
    "      <div class='led-state'>State B: Connected</div>\n"
    "      <div class='pattern-timing'>Pattern: ■ 200ms ON | ■ 200ms OFF (400ms cycle)</div>\n"
    "      <div style='color: #666; font-size: 0.9em;'>Receiving ESP-NOW packets, system operational</div>\n"
    "    </div>\n"
    "    <div class='led-pattern'>\n"
    "      <div class='led-state'>State C: Webserver Mode</div>\n"
    "      <div class='pattern-timing'>Pattern: ■ 200ms ON | ■ 100ms OFF | ■ 200ms ON | ■ 500ms OFF (1000ms cycle)</div>\n"
    "      <div style='color: #666; font-size: 0.9em;'>Configuration mode active (ESP-NOW stopped)</div>\n"
    "    </div>\n"
    "  </div>\n"
    "\n"
    "  <div class='status-section'>\n"
    "    <h2>Channel & Light Feedback</h2>\n"
    "    <p style='color: #666; font-size: 0.9em;'>Live input values from sender device:</p>\n"
    "    <div id='channelFeedback'>\n"
    "      <div style='margin: 12px 0;'>\n"
    "        <div style='display: flex; justify-content: space-between; margin-bottom: 4px;'>\n"
    "          <span style='font-weight: bold; color: #555;'>Channel 1:</span>\n"
    "          <span id='ch1_val' style='font-family: monospace; color: #2196F3;'>0/4095</span>\n"
    "        </div>\n"
    "        <div style='background: #e0e0e0; height: 20px; border-radius: 3px; overflow: hidden;'>\n"
    "          <div id='ch1_bar' style='background: #2196F3; height: 100%; width: 0%; transition: width 0.1s;'></div>\n"
    "        </div>\n"
    "      </div>\n"
    "      <div style='margin: 12px 0;'>\n"
    "        <div style='display: flex; justify-content: space-between; margin-bottom: 4px;'>\n"
    "          <span style='font-weight: bold; color: #555;'>Channel 2:</span>\n"
    "          <span id='ch2_val' style='font-family: monospace; color: #2196F3;'>0/4095</span>\n"
    "        </div>\n"
    "        <div style='background: #e0e0e0; height: 20px; border-radius: 3px; overflow: hidden;'>\n"
    "          <div id='ch2_bar' style='background: #2196F3; height: 100%; width: 0%; transition: width 0.1s;'></div>\n"
    "        </div>\n"
    "      </div>\n"
    "      <div style='margin: 12px 0;'>\n"
    "        <div style='display: flex; justify-content: space-between; margin-bottom: 4px;'>\n"
    "          <span style='font-weight: bold; color: #555;'>Channel 3:</span>\n"
    "          <span id='ch3_val' style='font-family: monospace; color: #2196F3;'>0/4095</span>\n"
    "        </div>\n"
    "        <div style='background: #e0e0e0; height: 20px; border-radius: 3px; overflow: hidden;'>\n"
    "          <div id='ch3_bar' style='background: #2196F3; height: 100%; width: 0%; transition: width 0.1s;'></div>\n"
    "        </div>\n"
    "      </div>\n"
    "      <div style='margin: 12px 0;'>\n"
    "        <div style='display: flex; justify-content: space-between; margin-bottom: 4px;'>\n"
    "          <span style='font-weight: bold; color: #555;'>Channel 4:</span>\n"
    "          <span id='ch4_val' style='font-family: monospace; color: #2196F3;'>0/4095</span>\n"
    "        </div>\n"
    "        <div style='background: #e0e0e0; height: 20px; border-radius: 3px; overflow: hidden;'>\n"
    "          <div id='ch4_bar' style='background: #2196F3; height: 100%; width: 0%; transition: width 0.1s;'></div>\n"
    "        </div>\n"
    "      </div>\n"
    "      <div style='margin: 12px 0;'>\n"
    "        <div style='display: flex; justify-content: space-between; margin-bottom: 4px;'>\n"
    "          <span style='font-weight: bold; color: #555;'>Channel 5:</span>\n"
    "          <span id='ch5_val' style='font-family: monospace; color: #2196F3;'>0/4095</span>\n"
    "        </div>\n"
    "        <div style='background: #e0e0e0; height: 20px; border-radius: 3px; overflow: hidden;'>\n"
    "          <div id='ch5_bar' style='background: #2196F3; height: 100%; width: 0%; transition: width 0.1s;'></div>\n"
    "        </div>\n"
    "      </div>\n"
    "      <div style='margin: 12px 0;'>\n"
    "        <div style='display: flex; justify-content: space-between; margin-bottom: 4px;'>\n"
    "          <span style='font-weight: bold; color: #555;'>Channel 6:</span>\n"
    "          <span id='ch6_val' style='font-family: monospace; color: #2196F3;'>0/4095</span>\n"
    "        </div>\n"
    "        <div style='background: #e0e0e0; height: 20px; border-radius: 3px; overflow: hidden;'>\n"
    "          <div id='ch6_bar' style='background: #2196F3; height: 100%; width: 0%; transition: width 0.1s;'></div>\n"
    "        </div>\n"
    "      </div>\n"
    "    </div>\n"
    "    <h3 style='margin-top: 20px; margin-bottom: 10px;'>Lights</h3>\n"
    "    <div style='display: grid; grid-template-columns: repeat(4, 1fr); gap: 10px;'>\n"
    "      <div style='text-align: center;'>\n"
    "        <div id='light1' style='width: 60px; height: 60px; margin: 0 auto 8px; border-radius: 50%; background: #ccc; border: 2px solid #999; transition: all 0.1s;'></div>\n"
    "        <span style='font-weight: bold; color: #555;'>Light 1</span>\n"
    "      </div>\n"
    "      <div style='text-align: center;'>\n"
    "        <div id='light2' style='width: 60px; height: 60px; margin: 0 auto 8px; border-radius: 50%; background: #ccc; border: 2px solid #999; transition: all 0.1s;'></div>\n"
    "        <span style='font-weight: bold; color: #555;'>Light 2</span>\n"
    "      </div>\n"
    "      <div style='text-align: center;'>\n"
    "        <div id='light3' style='width: 60px; height: 60px; margin: 0 auto 8px; border-radius: 50%; background: #ccc; border: 2px solid #999; transition: all 0.1s;'></div>\n"
    "        <span style='font-weight: bold; color: #555;'>Light 3</span>\n"
    "      </div>\n"
    "      <div style='text-align: center;'>\n"
    "        <div id='light4' style='width: 60px; height: 60px; margin: 0 auto 8px; border-radius: 50%; background: #ccc; border: 2px solid #999; transition: all 0.1s;'></div>\n"
    "        <span style='font-weight: bold; color: #555;'>Light 4</span>\n"
    "      </div>\n"
    "    </div>\n"
    "  </div>\n"
    "\n"
    "  <div class='status-section'>\n"
    "    <form id='settingsForm'>\n"
    "      <div class='form-group'>\n"
    "        <label>Device Role:</label>\n"
    "        <select name='device_role'>\n"
    "          <option value='0'>Receiver</option>\n"
    "          <option value='1'>Sender</option>\n"
    "        </select>\n"
    "      </div>\n"
    "      <div class='form-group'>\n"
    "        <label>Peer MAC Address (XX:XX:XX:XX:XX:XX):</label>\n"
    "        <input type='text' name='peer_mac' placeholder='FF:FF:FF:FF:FF:FF'>\n"
    "      </div>\n"
    "      <div class='form-group'>\n"
    "        <label>ESP-NOW Channel (1-13):</label>\n"
    "        <input type='number' name='channel' min='1' max='13' value='1'>\n"
    "      </div>\n"
    "      <h3>Proportional Channel Calibration</h3>\n"
    "      <div class='form-group'>\n"
    "        <label>Channel 1 Min:</label>\n"
    "        <input type='number' name='ch1_min' min='0' max='4095'>\n"
    "      </div>\n"
    "      <div class='form-group'>\n"
    "        <label>Channel 1 Max:</label>\n"
    "        <input type='number' name='ch1_max' min='0' max='4095'>\n"
    "      </div>\n"
    "      <div class='form-group'>\n"
    "        <label>Channel 2 Min:</label>\n"
    "        <input type='number' name='ch2_min' min='0' max='4095'>\n"
    "      </div>\n"
    "      <div class='form-group'>\n"
    "        <label>Channel 2 Max:</label>\n"
    "        <input type='number' name='ch2_max' min='0' max='4095'>\n"
    "      </div>\n"
    "      <div class='form-group'>\n"
    "        <label>Channel 3 Min:</label>\n"
    "        <input type='number' name='ch3_min' min='0' max='4095'>\n"
    "      </div>\n"
    "      <div class='form-group'>\n"
    "        <label>Channel 3 Max:</label>\n"
    "        <input type='number' name='ch3_max' min='0' max='4095'>\n"
    "      </div>\n"
    "      <div class='form-group'>\n"
    "        <label>Channel 4 Min:</label>\n"
    "        <input type='number' name='ch4_min' min='0' max='4095'>\n"
    "      </div>\n"
    "      <div class='form-group'>\n"
    "        <label>Channel 4 Max:</label>\n"
    "        <input type='number' name='ch4_max' min='0' max='4095'>\n"
    "      </div>\n"
    "      <div class='form-group'>\n"
    "        <label>Channel 5 Min:</label>\n"
    "        <input type='number' name='ch5_min' min='0' max='4095'>\n"
    "      </div>\n"
    "      <div class='form-group'>\n"
    "        <label>Channel 5 Max:</label>\n"
    "        <input type='number' name='ch5_max' min='0' max='4095'>\n"
    "      </div>\n"
    "      <div class='form-group'>\n"
    "        <label>Channel 6 Min:</label>\n"
    "        <input type='number' name='ch6_min' min='0' max='4095'>\n"
    "      </div>\n"
    "      <div class='form-group'>\n"
    "        <label>Channel 6 Max:</label>\n"
    "        <input type='number' name='ch6_max' min='0' max='4095'>\n"
    "      </div>\n"
    "      <h3>Per-Channel Servo & Rate Configuration</h3>\n"
    "      <div style='background: #f0f0f0; padding: 15px; border-radius: 5px;'>\n"
    "        <div style='display: grid; grid-template-columns: repeat(3, 1fr); gap: 15px;'>\n"
    "          <div>\n"
    "            <strong>Channel 1</strong>\n"
    "            <div><label>Min (µs):</label><input type='number' name='ch1_smin' min='500' max='2500'></div>\n"
    "            <div><label>Center (µs):</label><input type='number' name='ch1_sctr' min='500' max='2500'></div>\n"
    "            <div><label>Max (µs):</label><input type='number' name='ch1_smax' min='500' max='2500'></div>\n"
    "            <div><label>Expo (0.0-1.0):</label><input type='number' name='ch1_expo' min='0' max='1' step='0.05'></div>\n"
    "          </div>\n"
    "          <div>\n"
    "            <strong>Channel 2</strong>\n"
    "            <div><label>Min (µs):</label><input type='number' name='ch2_smin' min='500' max='2500'></div>\n"
    "            <div><label>Center (µs):</label><input type='number' name='ch2_sctr' min='500' max='2500'></div>\n"
    "            <div><label>Max (µs):</label><input type='number' name='ch2_smax' min='500' max='2500'></div>\n"
    "            <div><label>Expo (0.0-1.0):</label><input type='number' name='ch2_expo' min='0' max='1' step='0.05'></div>\n"
    "          </div>\n"
    "          <div>\n"
    "            <strong>Channel 3</strong>\n"
    "            <div><label>Min (µs):</label><input type='number' name='ch3_smin' min='500' max='2500'></div>\n"
    "            <div><label>Center (µs):</label><input type='number' name='ch3_sctr' min='500' max='2500'></div>\n"
    "            <div><label>Max (µs):</label><input type='number' name='ch3_smax' min='500' max='2500'></div>\n"
    "            <div><label>Expo (0.0-1.0):</label><input type='number' name='ch3_expo' min='0' max='1' step='0.05'></div>\n"
    "          </div>\n"
    "          <div>\n"
    "            <strong>Channel 4</strong>\n"
    "            <div><label>Min (µs):</label><input type='number' name='ch4_smin' min='500' max='2500'></div>\n"
    "            <div><label>Center (µs):</label><input type='number' name='ch4_sctr' min='500' max='2500'></div>\n"
    "            <div><label>Max (µs):</label><input type='number' name='ch4_smax' min='500' max='2500'></div>\n"
    "            <div><label>Expo (0.0-1.0):</label><input type='number' name='ch4_expo' min='0' max='1' step='0.05'></div>\n"
    "          </div>\n"
    "          <div>\n"
    "            <strong>Channel 5</strong>\n"
    "            <div><label>Min (µs):</label><input type='number' name='ch5_smin' min='500' max='2500'></div>\n"
    "            <div><label>Center (µs):</label><input type='number' name='ch5_sctr' min='500' max='2500'></div>\n"
    "            <div><label>Max (µs):</label><input type='number' name='ch5_smax' min='500' max='2500'></div>\n"
    "            <div><label>Expo (0.0-1.0):</label><input type='number' name='ch5_expo' min='0' max='1' step='0.05'></div>\n"
    "          </div>\n"
    "          <div>\n"
    "            <strong>Channel 6</strong>\n"
    "            <div><label>Min (µs):</label><input type='number' name='ch6_smin' min='500' max='2500'></div>\n"
    "            <div><label>Center (µs):</label><input type='number' name='ch6_sctr' min='500' max='2500'></div>\n"
    "            <div><label>Max (µs):</label><input type='number' name='ch6_smax' min='500' max='2500'></div>\n"
    "            <div><label>Expo (0.0-1.0):</label><input type='number' name='ch6_expo' min='0' max='1' step='0.05'></div>\n"
    "          </div>\n"
    "        </div>\n"
    "      </div>\n"
    "      <button type='submit'>Save Settings</button>\n"
    "      <button type='reset' class='reset'>Reset to Defaults</button>\n"
    "    </form>\n"
    "  </div>\n"
    "\n"
    "  <script>\n"
    "    // Update status display every 500ms\n"
    "    setInterval(function() {\n"
    "      fetch('/api/status')\n"
    "        .then(r => r.json())\n"
    "        .then(d => {\n"
    "          const connStatus = document.getElementById('connStatus');\n"
    "          const rssiValue = document.getElementById('rssiValue');\n"
    "          const ledPattern = document.getElementById('ledPattern');\n"
    "          const deviceMac = document.getElementById('deviceMac');\n"
    "          \n"
    "          // Update device MAC\n"
    "          if (d.device_mac) {\n"
    "            deviceMac.textContent = d.device_mac.toUpperCase();\n"
    "          }\n"
    "          \n"
    "          if (d.connected) {\n"
    "            connStatus.textContent = 'Connected';\n"
    "            connStatus.className = 'status-value status-connected';\n"
    "            rssiValue.textContent = d.rssi + ' dBm';\n"
    "          } else {\n"
    "            connStatus.textContent = 'Disconnected';\n"
    "            connStatus.className = 'status-value status-disconnected';\n"
    "            rssiValue.textContent = 'N/A';\n"
    "          }\n"
    "          \n"
    "          // Update channel bars and values (servo microseconds 1000-2000us)\n"
    "          for (let i = 0; i < 6; i++) {\n"
    "            const chNum = i + 1;\n"
    "            const us = d.servo_us[i];\n"
    "            const pct = ((us - 1000) / 1000 * 100).toFixed(0);\n"
    "            document.getElementById('ch' + chNum + '_val').textContent = us + 'µs';\n"
    "            document.getElementById('ch' + chNum + '_bar').style.width = pct + '%';\n"
    "          }\n"
    "          \n"
    "          // Update light indicators\n"
    "          for (let i = 0; i < 4; i++) {\n"
    "            const lightEl = document.getElementById('light' + (i + 1));\n"
    "            const isOn = (d.lights & (1 << i)) ? true : false;\n"
    "            if (isOn) {\n"
    "              lightEl.style.background = '#FFD700';\n"
    "              lightEl.style.borderColor = '#FFA500';\n"
    "              lightEl.style.boxShadow = '0 0 10px rgba(255, 215, 0, 0.8)';\n"
    "            } else {\n"
    "              lightEl.style.background = '#ccc';\n"
    "              lightEl.style.borderColor = '#999';\n"
    "              lightEl.style.boxShadow = 'none';\n"
    "            }\n"
    "          }\n"
    "        })\n"
    "        .catch(e => console.log('Status fetch error'));\n"
    "    }, 500);\n"
    "\n"
    "    document.getElementById('settingsForm').addEventListener('submit', function(e) {\n"
    "      e.preventDefault();\n"
    "      const data = new FormData(this);\n"
    "      const obj = {};\n"
    "      data.forEach((value, key) => obj[key] = value);\n"
    "      fetch('/api/settings', {\n"
    "        method: 'POST',\n"
    "        headers: { 'Content-Type': 'application/json' },\n"
    "        body: JSON.stringify(obj)\n"
    "      })\n"
    "        .then(r => r.json())\n"
    "        .then(r => alert(r.message))\n"
    "        .catch(e => alert('Error: ' + e));\n"
    "    });\n"
    "\n"
    "    fetch('/api/settings')\n"
    "      .then(r => r.json())\n"
    "      .then(d => {\n"
    "        document.querySelector('[name=device_role]').value = d.device_role;\n"
    "        document.querySelector('[name=peer_mac]').value = d.peer_mac;\n"
    "        document.querySelector('[name=channel]').value = d.channel;\n"
    "        for (let i = 1; i <= 6; i++) {\n"
    "          document.querySelector('[name=ch' + i + '_min]').value = d['ch' + i + '_min'];\n"
    "          document.querySelector('[name=ch' + i + '_max]').value = d['ch' + i + '_max'];\n"
    "          document.querySelector('[name=ch' + i + '_smin]').value = d['ch' + i + '_smin'];\n"
    "          document.querySelector('[name=ch' + i + '_sctr]').value = d['ch' + i + '_sctr'];\n"
    "          document.querySelector('[name=ch' + i + '_smax]').value = d['ch' + i + '_smax'];\n"
    "          document.querySelector('[name=ch' + i + '_expo]').value = d['ch' + i + '_expo'];\n"
    "        }\n"
    "      });\n"
    "  </script>\n"
    "</body>\n"
    "</html>";

#endif // WEBSERVER_PAGE_H
